"""
QXL Python Code Generator
==========================
Converts the QXL AST into executable Python source code using the
Visitor Pattern. The generated code is idiomatic Python.

QXL → Python Mappings:
    show "Hello"          →  print("Hello")
    read x                →  x = input()
    number x = 10         →  x = 10
    decimal pi = 3.14     →  pi = 3.14
    text name = "Alice"   →  name = "Alice"
    bool flag = true      →  flag = True
    if condition           →  if condition:
    otherwise             →  else:
    endif                 →  (dedent)
    repeat condition      →  while condition:
    endrepeat             →  (dedent)
    function foo(...)     →  def foo(...):
    endfunction           →  (dedent)
    &&                    →  and
    ||                    →  or
    !                     →  not

Usage:
    >>> from backend.generator import PythonGenerator
    >>> gen = PythonGenerator()
    >>> python_code, errors = gen.generate(ast)
"""

from __future__ import annotations

import os
from typing import Any, List, Optional, Tuple

from backend.ast_nodes import (
    ASTNode, ProgramNode, BlockNode, VarDeclNode, AssignNode,
    ShowNode, ReadNode, IfNode, RepeatNode, FunctionDeclNode,
    FunctionCallNode, ReturnNode, BreakNode, ContinueNode,
    BinOpNode, UnaryOpNode, ComparisonNode, LogicalNode,
    NumberLitNode, DecimalLitNode, StringLitNode, BoolLitNode,
    IdentifierNode,
)
from backend.errors import ErrorCollector, CodeGenError
from backend.utils import get_generated_dir, write_file


class PythonGenerator:
    """Generates executable Python code from a QXL AST.
    
    Handles indentation management, operator translation, and
    type conversion for all QXL constructs.
    """

    def __init__(self) -> None:
        self._lines: List[str] = []
        self._indent_level: int = 0
        self._indent_str: str = "    "   # 4 spaces
        self.errors: ErrorCollector = ErrorCollector()
        self._generated_code: str = ""

    def _indent(self) -> str:
        """Return the current indentation string."""
        return self._indent_str * self._indent_level

    def _emit_line(self, code: str) -> None:
        """Append an indented line of Python code."""
        self._lines.append(f"{self._indent()}{code}")

    def _emit_blank(self) -> None:
        """Append a blank line."""
        self._lines.append("")

    # ═════════════════════════════════════════════════════════════
    # PUBLIC API
    # ═════════════════════════════════════════════════════════════

    def generate(self, ast: ProgramNode) -> Tuple[str, ErrorCollector]:
        """Generate Python code from the AST.
        
        Returns:
            Tuple of (python_source_code, errors).
        """
        self._lines = []
        self._indent_level = 0
        self.errors = ErrorCollector()

        if ast is None:
            self.errors.add(CodeGenError("No AST provided for code generation"))
            return "", self.errors

        # Header comment
        self._lines.append("# ─── Generated by QXL Compiler ───")
        self._lines.append("# QuadX Programming Language → Python")
        self._lines.append("")

        self._visit(ast)

        self._generated_code = "\n".join(self._lines) + "\n"
        return self._generated_code, self.errors

    def get_code(self) -> str:
        """Return the last generated Python code."""
        return self._generated_code

    def save_to_file(self) -> str:
        """Save generated Python to generated/output.py and return the path."""
        filepath = os.path.join(get_generated_dir(), "output.py")
        write_file(filepath, self._generated_code)
        return filepath

    # ═════════════════════════════════════════════════════════════
    # VISITOR DISPATCH
    # ═════════════════════════════════════════════════════════════

    def _visit(self, node: ASTNode) -> str:
        """Dispatch to the appropriate visit method."""
        method_name = f"_visit_{node.__class__.__name__}"
        method = getattr(self, method_name, None)
        if method is None:
            self.errors.add(CodeGenError(
                f"Code generator does not handle {node.__class__.__name__}",
                line=node.line
            ))
            return ""
        return method(node)

    # ═════════════════════════════════════════════════════════════
    # VISITOR METHODS
    # ═════════════════════════════════════════════════════════════

    def _visit_ProgramNode(self, node: ProgramNode) -> str:
        # Separate functions from main body statements
        functions = []
        main_stmts = []
        for stmt in node.body:
            if isinstance(stmt, FunctionDeclNode):
                functions.append(stmt)
            else:
                main_stmts.append(stmt)

        # Generate functions first
        for func in functions:
            self._visit(func)
            self._emit_blank()

        # Generate main body
        if main_stmts:
            self._emit_line("# ─── Main Program ───")
            for stmt in main_stmts:
                self._visit(stmt)

        return ""

    def _visit_BlockNode(self, node: BlockNode) -> str:
        for stmt in node.statements:
            self._visit(stmt)
        return ""

    # ── Declarations & Assignments ──────────────────────────────

    def _visit_VarDeclNode(self, node: VarDeclNode) -> str:
        if node.value is not None:
            val = self._visit_expr(node.value)
            self._emit_line(f"{node.name} = {val}")
        else:
            # Default initialization based on type
            defaults = {
                "number": "0",
                "decimal": "0.0",
                "text": '""',
                "bool": "False",
            }
            default_val = defaults.get(node.var_type, "None")
            self._emit_line(f"{node.name} = {default_val}")
        return ""

    def _visit_AssignNode(self, node: AssignNode) -> str:
        val = self._visit_expr(node.value)
        self._emit_line(f"{node.name} = {val}")
        return ""

    # ── I/O ─────────────────────────────────────────────────────

    def _visit_ShowNode(self, node: ShowNode) -> str:
        val = self._visit_expr(node.value)
        self._emit_line(f"print({val})")
        return ""

    def _visit_ReadNode(self, node: ReadNode) -> str:
        self._emit_line(f"{node.name} = input()")
        return ""

    # ── Control Flow ────────────────────────────────────────────

    def _visit_IfNode(self, node: IfNode) -> str:
        cond = self._visit_expr(node.condition)
        self._emit_line(f"if {cond}:")

        self._indent_level += 1
        if node.then_body:
            for stmt in node.then_body:
                self._visit(stmt)
        else:
            self._emit_line("pass")
        self._indent_level -= 1

        if node.else_body:
            self._emit_line("else:")
            self._indent_level += 1
            for stmt in node.else_body:
                self._visit(stmt)
            self._indent_level -= 1

        return ""

    def _visit_RepeatNode(self, node: RepeatNode) -> str:
        cond = self._visit_expr(node.condition)
        self._emit_line(f"while {cond}:")

        self._indent_level += 1
        if node.body:
            for stmt in node.body:
                self._visit(stmt)
        else:
            self._emit_line("pass")
        self._indent_level -= 1

        return ""

    def _visit_BreakNode(self, node: BreakNode) -> str:
        self._emit_line("break")
        return ""

    def _visit_ContinueNode(self, node: ContinueNode) -> str:
        self._emit_line("continue")
        return ""

    # ── Functions ───────────────────────────────────────────────

    def _visit_FunctionDeclNode(self, node: FunctionDeclNode) -> str:
        params = ", ".join(p.name for p in node.params)
        self._emit_line(f"def {node.name}({params}):")

        self._indent_level += 1
        if node.body:
            for stmt in node.body:
                self._visit(stmt)
        else:
            self._emit_line("pass")
        self._indent_level -= 1

        return ""

    def _visit_FunctionCallNode(self, node: FunctionCallNode) -> str:
        args = ", ".join(self._visit_expr(a) for a in node.args)
        call_expr = f"{node.name}({args})"
        # When used as a statement (not inside an expression)
        self._emit_line(call_expr)
        return call_expr

    def _visit_ReturnNode(self, node: ReturnNode) -> str:
        if node.value is not None:
            val = self._visit_expr(node.value)
            self._emit_line(f"return {val}")
        else:
            self._emit_line("return")
        return ""

    # ═════════════════════════════════════════════════════════════
    # EXPRESSION VISITOR (returns string expression, no emit)
    # ═════════════════════════════════════════════════════════════

    def _visit_expr(self, node: ASTNode) -> str:
        """Visit an expression node and return its Python code string.
        
        Unlike _visit(), this does NOT emit lines — it returns the
        expression text for embedding in a statement.
        """
        if isinstance(node, BinOpNode):
            left = self._visit_expr(node.left)
            right = self._visit_expr(node.right)
            op = node.op
            # Python uses // for integer division — but QXL uses / which maps to /
            return f"({left} {op} {right})"

        elif isinstance(node, UnaryOpNode):
            operand = self._visit_expr(node.operand)
            if node.op == "!":
                return f"(not {operand})"
            return f"(-{operand})"

        elif isinstance(node, ComparisonNode):
            left = self._visit_expr(node.left)
            right = self._visit_expr(node.right)
            return f"({left} {node.op} {right})"

        elif isinstance(node, LogicalNode):
            left = self._visit_expr(node.left)
            right = self._visit_expr(node.right)
            op = "and" if node.op == "&&" else "or"
            return f"({left} {op} {right})"

        elif isinstance(node, NumberLitNode):
            return str(node.value)

        elif isinstance(node, DecimalLitNode):
            return str(node.value)

        elif isinstance(node, StringLitNode):
            # Escape any special characters
            escaped = node.value.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'

        elif isinstance(node, BoolLitNode):
            return "True" if node.value else "False"

        elif isinstance(node, IdentifierNode):
            return node.name

        elif isinstance(node, FunctionCallNode):
            args = ", ".join(self._visit_expr(a) for a in node.args)
            return f"{node.name}({args})"

        else:
            self.errors.add(CodeGenError(
                f"Unknown expression type: {node.__class__.__name__}",
                line=node.line
            ))
            return "None"
