"""
QXL Code Generator Unit Tests
===============================
Tests Python code generation correctness for all QXL constructs.
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest
from backend.lexer import QXLLexer
from backend.parser import QXLParser
from backend.generator import PythonGenerator


def generate(code: str) -> str:
    """Helper: parse QXL code and generate Python."""
    lexer = QXLLexer()
    parser = QXLParser()
    ast, _ = parser.parse(code, lexer)
    gen = PythonGenerator()
    python_code, _ = gen.generate(ast)
    return python_code


class TestGeneratorStatements:
    """Test statement code generation."""

    def test_show_string(self):
        py = generate('start\nshow "Hello"\nend')
        assert 'print("Hello")' in py

    def test_show_number(self):
        py = generate("start\nshow 42\nend")
        assert "print(42)" in py

    def test_var_decl(self):
        py = generate("start\nnumber x = 10\nend")
        assert "x = 10" in py

    def test_var_decl_default(self):
        py = generate("start\nnumber x\nend")
        assert "x = 0" in py

    def test_text_default(self):
        py = generate("start\ntext s\nend")
        assert 's = ""' in py

    def test_assignment(self):
        py = generate("start\nnumber x = 1\nx = 5\nend")
        assert "x = 5" in py


class TestGeneratorExpressions:
    """Test expression code generation."""

    def test_arithmetic(self):
        py = generate("start\nshow 1 + 2\nend")
        assert "1 + 2" in py

    def test_comparison(self):
        py = generate("start\nnumber x = 1\nif x > 5\nshow x\nendif\nend")
        assert "x > 5" in py

    def test_logical_and(self):
        py = generate("start\nbool a = true\nbool b = false\nif a && b\nshow 1\nendif\nend")
        assert " and " in py

    def test_logical_or(self):
        py = generate("start\nbool a = true\nbool b = false\nif a || b\nshow 1\nendif\nend")
        assert " or " in py

    def test_logical_not(self):
        py = generate("start\nbool a = true\nif !a\nshow 1\nendif\nend")
        assert "not " in py

    def test_bool_true(self):
        py = generate("start\nbool x = true\nend")
        assert "True" in py

    def test_bool_false(self):
        py = generate("start\nbool x = false\nend")
        assert "False" in py


class TestGeneratorControlFlow:
    """Test control flow code generation."""

    def test_if(self):
        py = generate("start\nnumber x = 1\nif x > 0\nshow x\nendif\nend")
        assert "if" in py
        assert ":" in py

    def test_if_otherwise(self):
        py = generate("start\nnumber x = 1\nif x > 0\nshow 1\notherwise\nshow 0\nendif\nend")
        assert "else:" in py

    def test_repeat(self):
        py = generate("start\nnumber i = 0\nrepeat i < 5\ni = i + 1\nendrepeat\nend")
        assert "while" in py

    def test_break(self):
        py = generate("start\nnumber i = 0\nrepeat i < 10\nbreak\nendrepeat\nend")
        assert "break" in py

    def test_continue(self):
        py = generate("start\nnumber i = 0\nrepeat i < 10\ncontinue\nendrepeat\nend")
        assert "continue" in py


class TestGeneratorFunctions:
    """Test function code generation."""

    def test_function_decl(self):
        py = generate("start\nfunction greet()\nshow \"hi\"\nendfunction\nend")
        assert "def greet():" in py

    def test_function_with_params(self):
        py = generate("start\nfunction add(number a, number b)\nreturn a + b\nendfunction\nend")
        assert "def add(a, b):" in py
        assert "return" in py

    def test_function_call(self):
        py = generate("start\nfunction greet()\nshow \"hi\"\nendfunction\ngreet()\nend")
        assert "greet()" in py

    def test_return(self):
        py = generate("start\nfunction f()\nreturn 42\nendfunction\nend")
        assert "return 42" in py


class TestGeneratorHeader:
    """Test generated code structure."""

    def test_has_header(self):
        py = generate("start\nend")
        assert "Generated by QXL Compiler" in py

    def test_generates_nonempty(self):
        py = generate('start\nshow "test"\nend')
        assert len(py.strip()) > 0
